server:
  port: 8084
spring:
  application:
    name: transaction-service
  cloud:
    config:
      uri: http://config-server:8888
  data:
    mongodb:
      uri: mongodb://mongodb:27017/bank_transactions

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
