server:
  port: 8081
spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://config-server:8888
  data:
    mongodb:
      uri: mongodb://mongodb:27017/bank_customers

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  redis:
    host: redis
    port: 6379
