server:
  port: 8082
spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank_accounts

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      uri: http://localhost:8888
