name: Build and Deploy to Contabo

on:
  push:
    branches: [ "main", "develop", "feature/*" ]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: 
          - account-service
          - api-gateway
          - config-server
          - credit-service
          - customer-service
          - eureka-server
          - ms-cars-api
          - transaction-service
          - yanki-service
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file ${{ matrix.service }}/pom.xml -DskipTests

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          # Convertir repository_owner a minúsculas porque docker no acepta mayúsculas en las imágenes
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/$OWNER/ms-banking-${{ matrix.service }}:latest"
          
          docker build -t $IMAGE_NAME ./${{ matrix.service }}
          docker push $IMAGE_NAME

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USER }}
          password: ${{ secrets.CONTABO_PASSWORD }}
          script: |
            # Entramos a la carpeta donde estará el proyecto en el servidor
            cd /opt/ms-banking
            
            # Hacemos login en GHCR en el servidor
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Descargamos las últimas imágenes y reiniciamos
            docker-compose pull
            docker-compose up -d
